DROP TABLE BOOK;
DROP TABLE AUTHOR;

create table AUTHOR (
    AUTHOR_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
) ENGINE=INNODB;

create table BOOK (
    BOOK_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    AUTHOR_ID VARCHAR(30) NOT NULL,
    YEAR VARCHAR(8),
    PUBLISHER VARCHAR(30),
    PRIMARY KEY (BOOK_ID),
    INDEX A_IND (AUTHOR_ID),
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHOR(AUTHOR_ID)
    ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE BOOK (
    BOOK_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL, 
    author_id MEDIUMINT,
    YEAR VARCHAR(8),
    PUBLISHER VARCHAR(30),
    PRIMARY KEY (BOOK_ID),
    INDEX aut_ind (author_id),
    FOREIGN KEY (author_id) 
        REFERENCES author(author_id)
        ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE parent (
    id INT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE child (
    id INT, 
    parent_id INT,
    INDEX par_ind (parent_id),
    FOREIGN KEY (parent_id) 
        REFERENCES parent(id)
        ON DELETE CASCADE
) ENGINE=INNODB;

INSERT INTO AUTHOR (NAME) VALUES ('J K Rowling');