#%RAML 0.8
title: Vijay RAML Library Service
version: v1
baseUri: http://example.com
protocols: [ HTTP ]
/addBook: 
  post: 
    body: 
      application/xml: 
    responses: 
      200: 
        body: 
          application/xml: 
/deleteBook: 
  post: 
    body: 
      application/xml: 
    responses: 
      200: 
        body: 
          application/xml: 
/findBook: 
  post: 
    body: 
      application/xml: 
    responses: 
      200: 
        body: 
          application/xml: 
/getBook: 
  post: 
    body: 
      application/xml: 
    responses: 
      200: 
        body: 
          application/xml: 
/updateBook: 
  post: 
    body: 
      application/xml: 
    responses: 
      200: 
        body: 
          application/xml: 
